nginx:
  build: nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "9086:9086"
php:
  build: ./
  container_name: lumen-php
  volumes:
    - ./:/app
  working_dir: /app/public
  command: chown -R :www-data /app
  command: chown www-data:www-data -R ../storage/ 
  command: chmod -R 777 /app
  command: chmod -R o+w /app/storage
  command: php-fpm
  links:
    - db
    - cache
  ports:
    - "9002:9002"
  environment:
    APP_ENV: local
    APP_DEBUG: True
    APP_KEY: 123
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db
    
    DB_DATABASE: lumen
    DB_USERNAME: lumen
    DB_PASSWORD: secret
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
db:
  image: mysql
  ports:
    - "3308:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret
cache:
  image: memcached
  ports:
    - "11311:11311"
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: lumen
    MYSQL_ROOT_PASSWORD: secret